#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode debian \
  --distribution trixie \
  --parent-distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --parent-archive-areas "main contrib non-free-firmware" \
  --mirror-bootstrap "http://deb.debian.org/debian" \
  --mirror-chroot "http://deb.debian.org/debian" \
  --mirror-binary "http://deb.debian.org/debian" \
  --mirror-chroot-security "http://security.debian.org/debian-security" \
  --mirror-binary-security "http://security.debian.org/debian-security" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash hostname=lotusos username=lotus" \
  --debian-installer false \
  --iso-application "LotusOS Live" \
  --iso-publisher "LotusOS Project" \
  --iso-volume "LotusOS amd64" \
  "${@}"
