#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --distribution trixie \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash hostname=lotusos username=lotus" \
  --debian-installer false \
  --image-name lotusos-amd64 \
  "${@}"
